In [1]:
import pandas as pd, numpy as np
import urllib

In [2]:
import gdal
from gdalconst import * 
import os, sys, time

gdal.AllRegister()
# gdal.GetDriverByName('EHdr').Register()

In [3]:
scoord = pd.read_csv('../modelDatasets/rm_seg_coords.csv')
cfile = scoord[['UID', 'latitude', 'longitude']]
cfile.head()

   UID   latitude   longitude
0    1  47.978215 -122.169366
1   27  47.978414 -122.133338
2   43  47.958874 -122.102727
3   66  47.947539 -122.070079
4   81  47.922928 -122.062374

In [4]:
months   = {1:'01', 2: '02', 3:'03', 4:'04', 5:'05', 6:'06', 7:'07', 8:'08', 9: '09',
               10:'10', 11:'11', 12:'12'}
days     = {1: 31, 2: 28, 3:31, 4:30, 5:31, 6:30, 7:31, 8:31, 9: 30,
               10:31, 11:30, 12:31}
lydays   = {1: 31, 2: 29, 3:31, 4:30, 5:31, 6:30, 7:31, 8:31, 9: 30,
               10:31, 11:30, 12:31}
def leapYear(year):
    if (year%400 == 0):
        return True
    elif (year%4 == 0) & (year%100 != 0):
        return True
    else:
        return False
    
import zipfile

def getDailyWeatherRaster(var):
    for year in np.arange(12)+1988:
        for m in np.arange(12)+1:
            month = months[m]
            if leapYear(year):
                ndays = lydays[m]
            else:
                ndays = days[m]
            for d in np.arange(ndays)+1:
                if d < 10:
                    day = '0' + str(d)
                else:
                    day = str(d)
                date = str(year) + month + day
                # unzipping a file
                fh = open("/Users/Alan/Desktop/ZipFiles/"+ var +'/'+ date + ".zip", "rb")
                z = zipfile.ZipFile(fh)
                # saving only the .bil file
                for name in z.namelist():
                    outpath = "../RasterFiles/" + var +'/'+ date
                    z.extract(name, outpath)
                fh.close()

In [5]:
# var = 'tmin'
# year = 1988
# month = '01'
# ndays = 31

# for d in np.arange(ndays)+1:
#     if d < 10:
#         day = '0' + str(d)
#     else:
#         day = str(d)
#     date = str(year) + month + day
#     # unzipping a file
#     fh = open("/Users/Alan/Desktop/ZipFiles/"+ var +'/'+ date + ".zip", "rb")
#     z = zipfile.ZipFile(fh)
#     # saving only the .bil file
#     for name in z.namelist():
#         outpath = "../RasterFiles/" + var +'/'+ date
#         z.extract(name, outpath)
#     fh.close()

In [15]:
def getValues(rasterDS, locData):
    size = len(locData)
    xValues = np.array(locData.loc[:, 'longitude'])
    yValues = np.array(locData.loc[:, 'latitude'])
    rows = rasterDS.RasterYSize #number of rows
    cols = rasterDS.RasterXSize # number of columns
    bands = rasterDS.RasterCount # number of data value types (it's going to be 1 for our case)
    
    # get georeference info
    transform = rasterDS.GetGeoTransform()
    xOrigin = transform[0]
    yOrigin = transform[3]
    pixelWidth = transform[1]
    pixelHeight = transform[5]
    
    band = rasterDS.GetRasterBand(1)
    # getting all data at once
    allData = band.ReadAsArray(0,0, cols, rows)
    
    #Result list
    result = []
    
    for i in range(size):
        # get x, y
        x = xValues[i]
        y = yValues[i]
        # compute pixel offset
        xOffset = int((x - xOrigin) / pixelWidth)
        yOffset = int((y - yOrigin) / pixelHeight)
        value   = allData[yOffset, xOffset]
        result.append(value)
    
    return result

In [27]:
base_file = '/Users/Alan/Desktop/RasterFiles/'
prism_base1 = '_stable_4kmD1_'
prism_base2 = '_stable_4kmD2_'
def getDailyWeatherData(var, cfile, prism_base):
    df = pd.DataFrame(index= [1], columns=np.arange(370)+1)
    df.columns = ['UID', 'latitude', 'longitude', 'Year'] + list(np.arange(366)+1)
    for year in np.arange(12)+1988:
        startTime = time.time() #if timing the function speed is really necessary
        data = cfile.copy()
        data['Year'] = year
        day_count = 1
        for m in np.arange(12)+1:
            month = months[m]
            if leapYear(year):
                ndays = lydays[m]
            else:
                ndays = days[m]
            for d in np.arange(ndays)+1:
                if d < 10:
                    day = '0' + str(d)
                else:
                    day = str(d)
                date = str(year) + month + day
                # raster file
                file_name = base_file + var +'/'+ date +'/'+ 'PRISM_' + var + prism_base + date + "_bil.bil"
                ds = gdal.Open(file_name)
                if ds is None:
                    print 'could not open ' + file_name
                    sys.exit(1)
                # weather data extracted using getValues function
                dailyData = getValues(ds, cfile)
                data[day_count] = dailyData
                day_count += 1
        if day_count < 365:
            print 'Error, check and see whether you have all the required files'
            sys.exit(1)
        elif day_count == 365:
            data[366] = None
        else:
            pass
        endTime = time.time()
        print 'The script took ' + str(endTime - startTime) + 'seconds'   
        df = pd.concat([df, data])
    return df

In [28]:
dPPT = getDailyWeatherData('ppt', cfile, prism_base2)
dTMAX = getDailyWeatherData('tmax', cfile, prism_base1)
# dTMIN = getDailyWeatherData('tmin', cfile, prism_base1)

The script took 34.2705538273seconds
The script took 37.1314060688seconds
The script took 37.3426170349seconds
The script took 37.5870499611seconds
The script took 40.6575767994seconds
The script took 42.6740891933seconds
The script took 42.0377290249seconds
The script took 41.4694080353seconds
The script took 43.3203780651seconds
The script took 50.4964578152seconds
The script took 47.0256459713seconds
The script took 57.0216758251seconds
The script took 39.048058033seconds
The script took 95.7758169174seconds
The script took 169.84248805seconds
The script took 38.894382seconds
The script took 45.3207960129seconds
The script took 44.797109127seconds
The script took 45.5138659477seconds
The script took 44.7066130638seconds
The script took 52.7284829617seconds
The script took 46.5905511379seconds
The script took 48.3133480549seconds
The script took 40.6031498909seconds

In [29]:
dPPT.head()

,1,2,3,4,5,6,7,8,9,10,...,361,362,363,364,365,366,UID,Year,latitude,longitude
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0,0,0,0,0,0,0,1.24,0.00,...,0,0,0,0.00,18.230000,2.81,1,1988,47.978215,-122.169366
1,0,0,0,0,0,0,0,0,1.77,0.02,...,0,0,0,0.02,20.190001,3.17,27,1988,47.978414,-122.133338
2,0,0,0,0,0,0,0,0,2.60,1.33,...,0,0,0,0.40,23.889999,4.01,43,1988,47.958874,-122.102727
3,0,0,0,0,0,0,0,0,2.60,1.33,...,0,0,0,0.40,23.889999,4.01,66,1988,47.947539,-122.070079

In [30]:
dTMAX.head()

,1,2,3,4,5,6,7,8,9,10,...,361,362,363,364,365,366,UID,Year,latitude,longitude
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,6.69,4.42,4.29,4.09,4.09,6.14,8.40,9.36,4.02,8.06,...,5.87,2.23,5.35,5.73,10.41,10.61,1,1988,47.978215,-122.169366
1,6.40,4.28,4.10,4.05,4.03,6.06,8.06,8.92,4.00,7.80,...,5.50,2.08,5.08,5.36,10.14,10.13,27,1988,47.978414,-122.133338
2,6.30,4.28,4.04,4.18,4.15,6.13,7.83,8.58,4.12,7.64,...,5.26,1.98,4.92,5.03,9.92,9.72,43,1988,47.958874,-122.102727
3,6.30,4.28,4.04,4.18,4.15,6.13,7.83,8.58,4.12,7.64,...,5.26,1.98,4.92,5.03,9.92,9.72,66,1988,47.947539,-122.070079

In [32]:
print len(dPPT)
print len(dPPT) == len(dTMAX)
print 1960*12+1

23521
True
23521

In [26]:
for i in np.arange(20):
    if i%2 == 0:
        print i
    else:
        pass
    print 'i love you'

0
i love you
i love you
2
i love you
i love you
4
i love you
i love you
6
i love you
i love you
8
i love you
i love you
10
i love you
i love you
12
i love you
i love you
14
i love you
i love you
16
i love you
i love you
18
i love you
i love you

In [8]:
# os.chdir(r'../RasterFiles/19880101')
# gdal.AllRegister()
# os.getcwd()
# os.path.dirname(os.path.realpath('PRISM_tmin_stable_4kmD1_19880101_bil.bil'))

In [9]:
# f = prism_base + '19880101' + "_bil.bil"
# print f
# f = r'../RasterFiles/19880101/PRISM_ppt_stable_4kmD2_19880101_bil.bil'
# ds = gdal.Open(f, GA_ReadOnly)
# print ds
# dailyData = getValues(ds, cfile)
# len(dailyData)

In [13]:
# base_file = '../RasterFiles/'
# prism_base = 'PRISM_tmin_stable_4kmD1_'
# var = 'tmin'
# year = 1988
# month = '01'
# data = cfile.copy()
# data['Year'] = year
# day_count = 1
# ndays = 31
# # os.chdir(base_file + var +'/')
# for d in np.arange(ndays)+1:
#     if d < 10:
#         day = '0' + str(d)
#     else:
#         day = str(d)
#     date = str(year) + month + day
#     # raster file
#     file_name = base_file + var + '/' + date + '/' + prism_base + date + "_bil.bil"
#     print date
#     ds = gdal.Open(file_name)
#     if ds is None:
#         print 'could not open ' + file_name
#         sys.exit(1)
#     # weather data extracted using getValues function
#     dailyData = getValues(ds, cfile)
#     data[day_count] = dailyData
#     day_count += 1

In [34]:
a = np.array([-1,-3,-1.3, -0.5, 0.8])
b = abs(a)
c = np.arange(5)+1
d = b*c
print b
print c
print d

[ 1.   3.   1.3  0.5  0.8]
[1 2 3 4 5]
[ 1.   6.   3.9  2.   4. ]

In [14]:
# data.head()

In [ ]:
def RasterFilesData2Excel(variable, coordDataFrame):
    baseFile = '../RasterFiles'
    resFolder = 'C:\\Users\\Allan\\Dropbox\\2015\\Research Data\\Weather Variables\\'
    cal      = {1:'jan', 2: 'feb', 3:'mar', 4:'apr', 5:'may', 6:'jun', 7:'jul', 8:'aug', 9: 'sep',
               10:'oct', 11:'nov', 12:'dec'}
    if variable == 'Precipitation':
        link = '\\'
        for year in np.arange(33)+1981:
            getDataset(year, variable, coordDataFrame, baseFile, link)
        fileName = resFolder+ 'Ppt\\' + 'PrecipitationRecord1981_2013.xlsx'
        writer = pd.ExcelWriter(fileName)
        coordDataFrame.to_excel(writer)
    elif variable == 'MinTemp':
        fileName = resFolder + variable + '\\'
        for year in np.arange(33)+1981:
            link = '\\' + str(year)+'\\'
            record = fileName + str(year) + '.xlsx'
            for month in np.arange(12)+1:
                getDataset(cal[month], variable, coordDataFrame, baseFile, link)
            writer = pd.ExcelWriter(record)
            coordDataFrame.to_excel(writer, sheet_name=str(year))
            coordDataFrame = dataset[['Xmin', 'Xmax', 'Ymin', 'Ymax']]
    elif variable == 'MaxTemp':
        fileName = resFolder + variable + '\\'
        for year in np.arange(33)+1981:
            link = '\\' + str(year)+'\\' 
            record = fileName + str(year) + '.xlsx'
            for month in np.arange(12)+1:
                getDataset(cal[month], variable, coordDataFrame, baseFile, link)
            writer = pd.ExcelWriter(record)
            coordDataFrame.to_excel(writer, sheet_name=str(year))
            coordDataFrame = dataset[['Xmin', 'Xmax', 'Ymin', 'Ymax']]
    else:
        print 'Incorrent variable name. The accepted variable names include "Precipitation", "MinTemp", and "MaxTemp"'