In [1]:
import pandas as pd
import numpy as np
from lxml import objectify

In [2]:
path = "../Research Data/DatabaseFiles/SurveyDetails.txt"

In [3]:
cols = ["Year", "Rutting", "LWP Rutting", "RWP Rutting", "IRI", "Faulting", "PSC", "PPC", "PRC", "RCN", "DBR", "GRND", "ID"]

In [4]:
df = pd.read_table(path, sep=',', names = cols )

In [5]:
df.head()

,Year,Rutting,LWP Rutting,RWP Rutting,IRI,Faulting,PSC,PPC,PRC,RCN,DBR,GRND,ID
0,1981,NaN,NaN,NaN,119.091,NaN,0,77,NaN,NaN,NaN,NaN,1
1,1981,0.236,NaN,NaN,181.170,NaN,26,61,79,NaN,NaN,NaN,2
2,1981,0.236,NaN,NaN,85.518,NaN,87,85,79,NaN,NaN,NaN,3
3,1981,0.236,NaN,NaN,190.039,NaN,92,58,79,NaN,NaN,NaN,4
4,1981,0.236,NaN,NaN,87.418,NaN,4,84,79,NaN,NaN,NaN,5

In [6]:
df = df.sort(['ID', 'Year'], ascending=[True, True])

In [7]:
path2 = "../Research Data/DatabaseFiles/ACPIndexesCurrent.xlsx"

In [8]:
df2 = pd.read_excel(path2)

In [9]:
k         = range(len(df2))
commonIDs = np.array(df2.loc[k , 'Survey Details_Int ID'])

In [10]:
ndf = df.loc[df['ID'].isin(commonIDs)]

In [11]:
ndf.tail()

,Year,Rutting,LWP Rutting,RWP Rutting,IRI,Faulting,PSC,PPC,PRC,RCN,DBR,GRND,ID
2193666,2008,0.161,0.111,0.211,181.542,0.000,94,61,87,NaN,NaN,NaN,91005
2283558,2009,0.077,0.056,0.098,197.125,0.000,100,56,95,NaN,NaN,NaN,91005
2373778,2010,0.080,0.046,0.114,186.583,0.000,100,59,94,NaN,NaN,NaN,91005
2464176,2011,0.090,0.056,0.124,180.750,0.017,NaN,61,93,NaN,NaN,NaN,91005
2549568,2012,0.088,0.042,0.134,199.667,0.044,97,56,94,NaN,NaN,NaN,91005

In [12]:
ndf.loc[:,'newID'] = np.array(ndf.loc[:,'ID']) * np.array(ndf.loc[:,'Year'])

/Users/Alan/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/indexing.py:243: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/Users/Alan/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/indexing.py:407: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [13]:
ndf['ypID'] = np.array(range(len(ndf)))+1

/Users/Alan/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [14]:
sortdf = ndf.loc[ndf['PSC'] == 100]

In [15]:
k2 = sortdf.index.tolist()
rfIDs = np.array(sortdf.loc[k2 , 'ypID'])

In [16]:
reqIDs = np.unique(np.concatenate((rfIDs, (rfIDs+1), (rfIDs+2), (rfIDs+3), (rfIDs+4)), axis =0))

In [17]:
crackIniDF = ndf.loc[ndf['ypID'].isin(reqIDs)]

In [18]:
crackIniDF

,Year,Rutting,LWP Rutting,RWP Rutting,IRI,Faulting,PSC,PPC,PRC,RCN,DBR,GRND,ID,newID,ypID
346621,1988,NaN,NaN,NaN,87.418,NaN,100,84,NaN,NaN,NaN,NaN,3,5964,5
434618,1989,NaN,NaN,NaN,87.418,NaN,75,84,NaN,NaN,NaN,NaN,3,5967,6
522566,1990,0.236,NaN,NaN,72.848,NaN,75,88,79,NaN,NaN,NaN,3,5970,7
610676,1991,0.236,NaN,NaN,82.984,NaN,71,85,79,NaN,NaN,NaN,3,5973,8
698857,1992,0.157,NaN,NaN,84.567,NaN,71,85,87,NaN,NaN,NaN,3,5976,9
1134468,1997,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,3,5991,14
1222150,1998,0.161,NaN,NaN,88.368,NaN,100,84,87,NaN,NaN,NaN,3,5994,15
1308957,1999,0.153,NaN,NaN,60.496,NaN,85,90,88,NaN,NaN,NaN,3,5997,16
1397827,2000,0.197,NaN,NaN,40.415,NaN,92,94,83,NaN,NaN,NaN,3,6000,17
1485845,2001,0.240,NaN,NaN,58.215,NaN,92,91,79,NaN,NaN,NaN,3,6003,18
1574421,2002,0.350,NaN,NaN,54.921,NaN,86,91,67,NaN,NaN,NaN,3,6006,19
86549,1983,NaN,NaN,NaN,179.904,NaN,100,61,NaN,NaN,NaN,NaN,4,7932,32
173856,1984,NaN,NaN,NaN,165.967,NaN,83,65,NaN,NaN,NaN,NaN,4,7936,33
260289,1986,0.236,NaN,NaN,165.967,NaN,75,65,79,NaN,NaN,NaN,4,7944,34
346622,1988,0.236,NaN,NaN,105.788,NaN,78,80,79,NaN,NaN,NaN,4,7952,35
434619,1989,0.236,NaN,NaN,109.589,NaN,78,79,79,NaN,NaN,NaN,4,7956,36
522567,1990,NaN,NaN,NaN,109.589,NaN,100,79,NaN,NaN,NaN,NaN,4,7960,37
610677,1991,NaN,NaN,NaN,117.824,NaN,100,77,NaN,NaN,NaN,NaN,4,7964,38
698858,1992,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,4,7968,39
785564,1993,0.236,NaN,NaN,115.290,NaN,93,78,79,NaN,NaN,NaN,4,7972,40
873040,1994,NaN,NaN,NaN,NaN,NaN,93,NaN,NaN,NaN,NaN,NaN,4,7976,41
959753,1995,0.236,NaN,NaN,130.493,NaN,100,74,79,NaN,NaN,NaN,4,7980,42
1047154,1996,NaN,NaN,NaN,NaN,NaN,93,NaN,NaN,NaN,NaN,NaN,4,7984,43
1134469,1997,0.276,NaN,NaN,165.334,NaN,100,65,75,NaN,NaN,NaN,4,7988,44
1222151,1998,NaN,NaN,NaN,NaN,NaN,55,NaN,NaN,NaN,NaN,NaN,4,7992,45
1308958,1999,0.394,NaN,NaN,150.764,NaN,100,69,62,NaN,NaN,NaN,4,7996,46
1397828,2000,0.079,NaN,NaN,94.386,NaN,100,83,94,NaN,NaN,NaN,4,8000,47
1485846,2001,0.118,NaN,NaN,99.454,NaN,100,82,91,NaN,NaN,NaN,4,8004,48
1574422,2002,0.197,NaN,NaN,98.187,NaN,100,82,83,NaN,NaN,NaN,4,8008,49
1663660,2003,0.236,NaN,NaN,113.390,NaN,99,78,79,NaN,NaN,NaN,4,8012,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1397719,1999,0.110,NaN,NaN,143.289,NaN,100,71,92,NaN,NaN,NaN,90910,181729090,1527413
1485730,2000,0.150,NaN,NaN,150.764,NaN,100,69,88,NaN,NaN,NaN,90910,181820000,1527414
1574306,2001,0.134,NaN,NaN,186.872,NaN,100,59,89,NaN,NaN,NaN,90910,181910910,1527415
1663544,2002,0.134,NaN,NaN,183.831,NaN,88,60,89,NaN,NaN,NaN,90910,182001820,1527416
1752078,2003,0.118,NaN,NaN,197.641,NaN,96,56,91,NaN,NaN,NaN,90910,182092730,1527417
1841301,2004,0.194,0.192,0.197,197.451,NaN,90,56,84,NaN,NaN,NaN,90910,182183640,1527418
1930790,2005,0.212,0.196,0.229,193.694,NaN,85,57,82,NaN,NaN,NaN,90910,182274550,1527419
2549473,2012,0.123,0.084,0.162,226.700,0.032,100,48,90,NaN,NaN,NaN,90910,182910920,1527426
86528,1981,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,91005,180280905,1527427
173835,1983,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,91005,180462915,1527428
260268,1984,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,91005,180553920,1527429
346601,1986,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,91005,180735930,1527430
434598,1988,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,91005,180917940,1527431
522546,1989,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,91005,181008945,1527432
610656,1990,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,91005,181099950,1527433
698837,1991,0.236,NaN,NaN,NaN,NaN,84,NaN,79,NaN,NaN,NaN,91005,181190955,1527434
785543,1992,0.276,NaN,NaN,210.099,NaN,84,53,75,NaN,NaN,NaN,91005,181281960,1527435
873019,1993,NaN,NaN,NaN,NaN,NaN,84,NaN,NaN,NaN,NaN,NaN,91005,181372965,1527436
959732,1994,0.197,NaN,NaN,184.971,NaN,84,60,83,NaN,NaN,NaN,91005,181463970,1527437
1397810,1999,0.105,NaN,NaN,148.864,NaN,100,70,92,NaN,NaN,NaN,91005,181918995,1527442
1485825,2000,0.171,NaN,NaN,171.035,NaN,100,64,86,NaN,NaN,NaN,91005,182010000,1527443
1574401,2001,0.118,NaN,NaN,206.720,NaN,100,54,91,NaN,NaN,NaN,91005,182101005,1527444
1663639,2002,0.118,NaN,NaN,207.987,NaN,91,53,91,NaN,NaN,NaN,91005,182192010,1527445
1752173,2003,0.144,NaN,NaN,196.796,NaN,97,57,88,NaN,NaN,NaN,91005,182283015,1527446
1841396,2004,0.205,0.199,0.210,196.807,NaN,93,57,83,NaN,NaN,NaN,91005,182374020,1527447
1930885,2005,0.188,0.192,0.184,197.511,NaN,80,56,84,NaN,NaN,NaN,91005,182465025,1527448
2283558,2009,0.077,0.056,0.098,197.125,0.000,100,56,95,NaN,NaN,NaN,91005,182829045,1527452
2373778,2010,0.080,0.046,0.114,186.583,0.000,100,59,94,NaN,NaN,NaN,91005,182920050,1527453
2464176,2011,0.090,0.056,0.124,180.750,0.017,NaN,61,93,NaN,NaN,NaN,91005,183011055,1527454
2549568,2012,0.088,0.042,0.134,199.667,0.044,97,56,94,NaN,NaN,NaN,91005,183102060,1527455

In [19]:
path0 = "../Research Data/DatabaseFiles/"

In [20]:
#crackIniDF.to_csv(path0+'InitiationModelData.csv')

In [21]:
#ndf.to_csv(path0+'SortedData.csv')

In [27]:
testCorr_df = ndf.loc[:,["IRI","PSC"]]

In [28]:
testCorr_df.head()

           IRI  PSC
2       85.518   87
86548   87.418   79
173855  87.418   51
260288  96.286   51
346621  87.418  100

In [31]:
testCorr_df = testCorr_df[testCorr_df['IRI'].notnull()]

In [32]:
testCorr_df = testCorr_df[testCorr_df['PSC'].notnull()]

In [33]:
len(testCorr_df)

1290939

In [34]:
testCorr_df['IRI'].corr(testCorr_df['PSC'])

-0.30755153030311583